### ISSUE TITLE
Unable to output full pixel image from MERSCOPE data

### ISSUE THREAD

**Issue by stsai7** [seqscope/ficture#12]
Hi,

Thank you so much for creating this amazing tool! It works great on our MERSCOPE data and the data makes sense coming out when compared with our single cell RNA-seq results. The main issue I am having is that it seems like the full pixel-level image is only outputting part of the full image for some reason. The course images look okay and cover the whole section, so I am guessing something is going on with the pixel level decoding? When I checked the output files, I did notice that the *.pixel.sorted.tsv file only contains one block# (block 0) when the block size is 2000. I attached a screenshot of the head of the file.

<img width="858" alt="Screen Shot 2024-08-28 at 9 47 04 AM" src="https://github.com/user-attachments/assets/2756d0d5-4328-41ce-8427-44d5685d815f">

For reference as well, I ran Ficture using Python 3.11 with the PyPi installation and also tried the main branch version as well. I've been using the run together function, and haven't tried running the individual commands.

Any idea what is happening? Any help would be great. Thank you!

Best,
Steph

**Comment by hyunminkang** [comment]
Hi Steph. In my experience, that could happen if the input transcript file was not sorted by the major axis. Would that be the case?

**Comment by stsai7** [comment]
Yes sorting the file worked perfectly! Thank you so much!

**Comment by hyunminkang** [comment]
Thanks for the feedback @stsai7! I will close this issue then.
