### ISSUE TITLE
Preprocess of Stereo-seq data

### ISSUE THREAD

**Issue by camelest** [seqscope/ficture#15]
Hi, thank you so much for a great tool!

I was just wondering if you could share the preprocess of Stereo-seq data.
The embryo data in the paper look great.

Best,

**Comment by hyunminkang** [comment]
Hi @camelest -- You can download the raw Stereo-seq data from the original publication. As suggested please modify the pixel-level coordinates into micrometer-scale and apply --mu-scale 1 as discussed elsewhere.

**Comment by camelest** [comment]
@hyunminkang Thank you so much fo the clarification.
