### ISSUE TITLE
ERROR:root:Cannot find bgzip. Please make sure that the path to --bgzip is correct

### ISSUE THREAD

**Issue by jairaj-mathur** [seqscope/ficture#17]
Hi everyone.

I followed the steps of the quickstart, but when I try to do run_together, it gives the following error:
ERROR:root:Cannot find bgzip. Please make sure that the path to --bgzip is correct

Could anyone point what is the bgzip, and what path is it asking for?

Warm regards

Jairaj Mathur

**Comment by jairaj-mathur** [comment]
Hi everyone, I was able to resolve this error easily by providing the paths to bgzip and tabix

**Comment by LeilaBagha** [comment]
I have same error would you please advise me how did you resolve it? @jairaj-mathur

**Comment by jairaj-mathur** [comment]
@LeilaBagha, I just installed bc and tabix using:
sudo apt-get update
sudo apt-get install tabix -y
sudo apt-get install bc -y

and then it automatically got added to my path. Then it was able to find it.

try checking !which bc to see if this is installed on your system or not
