### ISSUE TITLE
OSError: [Errno 95] Operation not supported: (related to append csv in S3)

### ISSUE THREAD

**Issue by jairaj-mathur** [seqscope/ficture#19]
Hi all

Thank you for being so responsive regarding previous issues!  

I am running my full Visium HD dataset, but making spatial minibatches is failing. From my understanding, writing csvs from dataframe is using mode= 'a', which is append mode. In systems like databricks, connected to S3, this append operation is not supported. Additionally, writing out big files is not supported in the local environment in databricks, so S3 is the only option.
https://stackoverflow.com/questions/78284654/pandas-to-csv-cannot-append-to-file-in-databricks-cloud-oserror-errno-95-operat
Please let me know if there are any workarounds you can think of. Here is the full output:

INFO:root:Random seed 1728596338.997672
INFO:root:Read blocks of pixels: 18.69 x 330.96
INFO:root:Read blocks of pixels: 28.89 x 403.23
INFO:root:Read blocks of pixels: 38.19 x 482.53
INFO:root:Read blocks of pixels: 46.25 x 521.32
INFO:root:Read blocks of pixels: 53.79 x 549.53
INFO:root:Read blocks of pixels: 61.33 x 591.83
INFO:root:Read blocks of pixels: 68.68 x 630.60
INFO:root:Read blocks of pixels: 75.56 x 665.89
INFO:root:Read blocks of pixels: 82.15 x 701.12
INFO:root:Read blocks of pixels: 88.55 x 724.05
INFO:root:Read blocks of pixels: 94.67 x 743.41
INFO:root:Read blocks of pixels: 100.61 x 757.51
INFO:root:Read blocks of pixels: 106.72 x 768.11
INFO:root:Read blocks of pixels: 112.91 x 778.66
INFO:root:Read blocks of pixels: 119.18 x 787.51
INFO:root:Read blocks of pixels: 125.46 x 798.05
INFO:root:Read blocks of pixels: 131.73 x 808.66
INFO:root:Read blocks of pixels: 137.93 x 820.97
INFO:root:Read blocks of pixels: 144.27 x 829.85
INFO:root:Read blocks of pixels: 150.49 x 842.16
INFO:root:Read blocks of pixels: 156.62 x 850.99
INFO:root:Read blocks of pixels: 162.76 x 859.79
INFO:root:Read blocks of pixels: 168.93 x 870.34
INFO:root:Read blocks of pixels: 175.20 x 879.18
INFO:root:Read blocks of pixels: 181.66 x 886.20
INFO:root:Read blocks of pixels: 188.15 x 895.05
INFO:root:Read blocks of pixels: 194.70 x 900.37
INFO:root:Read blocks of pixels: 201.45 x 905.65
INFO:root:Read blocks of pixels: 208.43 x 912.69
INFO:root:Read blocks of pixels: 215.26 x 917.98
INFO:root:Read blocks of pixels: 222.20 x 925.07
INFO:root:Read blocks of pixels: 229.23 x 930.35
INFO:root:Read blocks of pixels: 236.60 x 937.41
INFO:root:Read blocks of pixels: 243.89 x 942.66
INFO:root:Read blocks of pixels: 250.89 x 947.91
INFO:root:Read blocks of pixels: 257.79 x 953.36
INFO:root:Read blocks of pixels: 264.60 x 958.81
INFO:root:Read blocks of pixels: 271.42 x 964.27
INFO:root:Read blocks of pixels: 278.22 x 969.71
INFO:root:Read blocks of pixels: 284.89 x 973.40
INFO:root:Read blocks of pixels: 291.85 x 977.10
INFO:root:Read blocks of pixels: 298.79 x 980.79
INFO:root:Read blocks of pixels: 305.81 x 986.24
INFO:root:Read blocks of pixels: 312.55 x 990.21
INFO:root:Read blocks of pixels: 319.21 x 995.58
INFO:root:Read blocks of pixels: 325.61 x 1004.33
INFO:root:Read blocks of pixels: 331.88 x 1009.64
INFO:root:Read blocks of pixels: 338.25 x 1013.13
INFO:root:Read blocks of pixels: 344.64 x 1016.78
INFO:root:Read blocks of pixels: 351.00 x 1022.50
INFO:root:Read blocks of pixels: 357.25 x 1025.70
INFO:root:Read blocks of pixels: 363.61 x 1029.40
INFO:root:Read blocks of pixels: 370.13 x 1033.07
INFO:root:Read blocks of pixels: 376.78 x 1036.75
INFO:root:Read blocks of pixels: 383.55 x 1040.47
INFO:root:Read blocks of pixels: 390.42 x 1044.15
INFO:root:Read blocks of pixels: 397.19 x 1051.95
INFO:root:Read blocks of pixels: 403.79 x 1059.14
INFO:root:Read blocks of pixels: 410.15 x 1066.36
INFO:root:Read blocks of pixels: 416.19 x 1073.13
INFO:root:Read blocks of pixels: 421.99 x 1082.09
INFO:root:Read blocks of pixels: 427.72 x 1094.57
INFO:root:Read blocks of pixels: 433.49 x 1114.09
INFO:root:Read blocks of pixels: 439.39 x 1129.46
INFO:root:Read blocks of pixels: 445.26 x 1143.71
INFO:root:Read blocks of pixels: 451.10 x 1154.26
INFO:root:Read blocks of pixels: 456.83 x 1161.44
INFO:root:Read blocks of pixels: 462.41 x 1173.57
INFO:root:Read blocks of pixels: 467.79 x 1178.99
INFO:root:Read blocks of pixels: 473.05 x 1186.17
INFO:root:Read blocks of pixels: 478.31 x 1194.69
INFO:root:Read blocks of pixels: 483.53 x 1200.10
INFO:root:Read blocks of pixels: 488.74 x 1205.52
INFO:root:Read blocks of pixels: 493.97 x 1210.93
INFO:root:Read blocks of pixels: 499.28 x 1216.34
INFO:root:Read blocks of pixels: 504.56 x 1221.76
INFO:root:Output region (504.78, 500.22) (45.4, 550.2) x (87.6, 587.8)
['X', 'random_index', 'Y', 'gene', 'Count']
Traceback (most recent call last):
  File "/databricks/python3/lib/python3.11/site-packages/pandas/io/formats/csvs.py", line 270, in save
    self._save()
  File "/databricks/python3/lib/python3.11/site-packages/pandas/io/formats/csvs.py", line 275, in _save
    self._save_body()
  File "/databricks/python3/lib/python3.11/site-packages/pandas/io/formats/csvs.py", line 313, in _save_body
    self._save_chunk(start_i, end_i)
  File "/databricks/python3/lib/python3.11/site-packages/pandas/io/formats/csvs.py", line 324, in _save_chunk
    libwriters.write_csv_rows(
  File "writers.pyx", line 73, in pandas._libs.writers.write_csv_rows
OSError: [Errno 95] Operation not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/databricks/python3/bin/ficture", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/databricks/python3/lib/python3.11/site-packages/ficture/cli.py", line 43, in main
    function(sys.argv[2:])
  File "/databricks/python3/lib/python3.11/site-packages/ficture/scripts/make_spatial_minibatch.py", line 157, in make_spatial_minibatch
    df.loc[indx, output_header].to_csv(args.output, mode='a', sep='\t', index=False, header=False, float_format='%.2f')
  File "/databricks/python3/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/databricks/python3/lib/python3.11/site-packages/pandas/core/generic.py", line 3967, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/databricks/python3/lib/python3.11/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/databricks/python3/lib/python3.11/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
  File "/databricks/python3/lib/python3.11/site-packages/pandas/io/common.py", line 157, in __exit__
    self.close()
  File "/databricks/python3/lib/python3.11/site-packages/pandas/io/common.py", line 144, in close
    handle.close()
OSError: [Errno 95] Operation not supported

**Comment by hyunminkang** [comment]
Currently, we only support standard file system.
