### ISSUE TITLE
License

### ISSUE THREAD

**Issue by heylf** [seqscope/ficture#2]
We are considering your method for inclusion in a spatial transcriptomics pipeline.

However your method does not have a LICENSE, [LICENSE.md](http://license.md/) or LICENSE.txt file containing the license text, in full, in the project's root directory, thus we are unsure if we can include your method.

We do of course acknowledge that it is entirely up to you which license you adopt (or whether you adopt a license at all) and how you display the license information. 

But if you are willing to make your method open for the scientific community please adopt an [OSI-approved license](https://opensource.org/licenses/) and include the license text (typically amended with the name of the copyright holder and the year the license is adopted), in full, in either one of the following files in your project's root directory: LICENSE, [LICENSE.md](http://license.md/), LICENSE.txt.

Thank you very much for your time and thank you for your work!

**Comment by Yichen-Si** [comment]
Hi, sorry for my oversight, we have the CC BY-NC 4.0  license but has not added to all branches, I'll fix it soon.
