### ISSUE TITLE
LDA with Prior knowledge

### ISSUE THREAD

**Issue by debienicolas** [seqscope/ficture#23]
Hi,

Thank you for this wonderful tool.

In the paper you write: 
>Alternatively, the factors can also be obtained from external sc- and sn-RNA-seq references datasets, or from other spatially agnostic methods such as Seurat[16](https://www.biorxiv.org/content/10.1101/2023.11.04.565621v2.full#ref-16) and  Scanpy[24](https://www.biorxiv.org/content/10.1101/2023.11.04.565621v2.full#ref-24) that learn factors based on grids. FICTURE can use these external factors as priors to initialize the LDA factors or use them directly as input factors.

How could I use prior knowledge to initialize the LDA factors? 

Thank you very much!

**Comment by hyunminkang** [comment]
While this feature is in an experimental stage, (we are working on several modifications to ensure that it works seamlessly as intended), we released this experimental feature in our latest push, and documented at https://seqscope.github.io/ficture/localrun/#optional-initializing-lda-model-from-pseudo-bulk-data
