### ISSUE TITLE
Matching `FICTURE` outputs to Visium bins

### ISSUE THREAD

**Issue by Nick-Eagles** [seqscope/ficture#25]
Hello,

I'd first like to mention that I'm aware of the similar previous issues #21 and #7. I was unable to re-open #21 and am therefore opening a new issue here, as the [suggested solution](https://github.com/seqscope/ficture/issues/7#issuecomment-2322263199) (based on `spatula join-pixel-tsv`) does not work (at least for my Visium HD data). Most notably, the `X` and `Y` columns in `transcripts_ficture_joined.tsv.gz` (generated by following the instructions [here](https://seqscope.github.io/spatula/tools/join_pixel_tsv/)) do not match the coordinates in the tissue positions file. For reference, here are the ranges of coordinates in the `transcripts_ficture_joined.tsv.gz` file (read into a `DataFrame` called `a`):

```
> sprintf('(%.1f, %.1f)', min(a$X), max(a$X))
[1] "(1908.4, 8639.9)"
> sprintf('(%.1f, %.1f)', min(a$Y), max(a$Y))
[1] "(6843.2, 13575.0)"
```

Here are the ranges of coordinates from the tissue positions file (read into a `SpatialExperiment` object):

```
> sprintf('(%.1f, %.1f)', min(spatialCoords(spe)[, 'pxl_col_in_fullres']), max(spatialCoords(spe)[, 'pxl_col_in_fullres']))
[1] "(42805.3, 84912.6)"
> sprintf('(%.1f, %.1f)', min(spatialCoords(spe)[, 'pxl_row_in_fullres']), max(spatialCoords(spe)[, 'pxl_row_in_fullres']))
[1] "(11937.6, 54044.3)"
```

Even if the coordinates did "match", I'm worried that matching by floating-point values is error-prone, and it's nontrivial to write code (such as in `R`) to line up a very large set of only approximately equal coordinates. For this reason, I believe many users would find it highly helpful to support matching by bin *barcode*, not coordinate.

Thanks for the work so far in developing and maintaining this very useful tool.

Best,
-Nick

**Comment by lcolladotor** [comment]
Thanks for documenting this need we have Nick! ^^

**Comment by Nick-Eagles** [comment]
I checked that I did run `ficture run_together` with `--mu-scale 1`, though I'm not sure what you mean by preparing the TSV file in micrometer scale. Regarding the matching by barcode and not coordinate, I realized that while it would still be helpful, it's maybe not critically important since rounding coordinates to some threshold is a fast and easy way to line up the floating-point coordinates.

**Comment by hyunminkang** [comment]
I see. In that case, you could have barcode information in your input TSV as additional column, and the joined tsv should contain the barcode as the column.

**Comment by XiaolongYang-HZAU** [comment]
> --mu-scale 1
Hello, I'm using the three files generated by a bin1 GEM file from BGI's stereo-seq to fit Ficture and set --mu-scale to 0.5 while running (since each bin1 from BGI is 0.5x0.5um). I noticed that currently spatula join-pixel-tsv hasn't updated the --mu-scale parameter. Does this mean that I should first multiply all the coordinate results output by Ficture by 2 to match the input TSV file before running spatula join-pixel-tsv? Thank you very much for the excellent tool you've developed. I'm looking forward to your reply and hope that join-pixel-tsv can be integrated into Ficture's standard process in the future to enhance usability.
