### ISSUE TITLE
tutorial  for FICTURE plotting

### ISSUE THREAD

**Issue by Bo-UT** [seqscope/ficture#4]
Hi, 

Nice tool! Thanks. 
Is the tutorial for plotting with FICTURE available yet?

**Comment by hyunminkang** [comment]
plotting commands are included in the tutorial. You may use run_together command to generate plots too.

**Comment by Bo-UT** [comment]
Great. Thanks a lot!

**Comment by Bo-UT** [comment]
Hi, 

I followed [Xenium formatting](https://seqscope.github.io/ficture/format_input/xenium/) and generated filtered.matrix.tsv.gz, but ran into an error 
`ERROR:root:There is no target to run. Please make sure that at least on run option was turned on`

Command I used: 
`ficture run_together --in-tsv filtered.matrix.tsv.gz --out-dir .`
Thank you!

**Comment by hyunminkang** [comment]
You need to add "--all" option (or specify at least one of the individual steps, such as --preprocess, --segment, etc)

**Comment by Bo-UT** [comment]
Great! I add `--all` and it works. Thanks a lot!
I want to plot the pixel image in a specific region, but how can I plot the coordinate space (transcript coordinate in the input `filtered.matrix.tsv.gz`) to pixel space. Are the limits of  `xmin`,`xmax`, `ymin` and `ymax` in `ficture plot_pixel_full` coordinate space? 
Thank you.

**Comment by hyunminkang** [comment]
Hi @Bo-UT, the xmin, xmax, ymin, ymax is based on the coordinate space of input X/Y coordinates of the TSV file.
