### ISSUE TITLE
no stereopy input in tutorial

### ISSUE THREAD

**Issue by Yiikea** [seqscope/ficture#8]
Dear Author,

I have been following your tutorial and found it immensely helpful. However, I noticed that the section on stereo-seq lacks detailed input instructions, which has made it challenging to apply the concepts in practice. To enhance the tutorial, could you please include stereo-seq input?

Thank you for your time and consideration.

Best regards

**Comment by hyunminkang** [comment]
Dear @Yiikea - thank you for your suggestion. You will need Stereo-seq's Bin1 matrix to convert the input into pixel level. Unfortunately, most of the released stereo-seq data does not release Bin1 matrix, so I think that the utility is limited for general use. 

Nevertheless, writing a script to prepare a pixel-level input data should be pretty straightforward. What you need is to convert X/Y coordinates in the Bin1 matrix into micrometer scale from the Bin1 matrix, and sort the data in one coordinate (typically Y axis or longer axis).
